// ─── Generated by V School Menu Editor + Claude ──────────────────────────────
//
// USAGE IN Sidebar.js:
//   import { canSeeItem } from '@/lib/sidebarProfiles';
//
//   // Inside the render loop — checked once per item using session role:
//   if (!canSeeItem(userRole, item.id)) return null;
//
// RULE: items with active === false are always hidden (handled in Sidebar.js).
// RULE: null means "all items visible" for that role.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Role → allowed item IDs whitelist.
 * null  = all items visible (no filtering).
 * []    = no items visible.
 * [...]  = explicit whitelist of item IDs.
 */
export const SIDEBAR_PROFILES = {
  // ── S1: Developer — full access ─────────────────────────────────────────
  DEV: null,

  // ── S2: Tech / IT — system + read all ───────────────────────────────────
  TEC: [
    'executive-analytics', 'tasks', 'audit-trail',
    'customers',
    'employees', 'team-kpi', 'admin-performance',
    'ai-config', 'system-config', 'settings',
  ],

  // ── R2: Management — all operational views, approve, reports ────────────
  MGR: [
    'executive-analytics', 'audit-trail',
    'pos-system', 'inventory-manager',
    'customers', 'facebook-chat', 'line-connect',
    'facebook-ads', 'campaign-tracking', 'analytics', 'notification-rules',
    'courses', 'schedules', 'recipes', 'packages', 'attendance-scanner',
    'kitchen-stock', 'inventory-control', 'procurement', 'assets',
    'employees', 'tasks', 'team-kpi', 'admin-performance',
  ],

  // ── R3: Marketing — ads + chat + courses + sales ────────────────────────
  MKT: [
    'executive-analytics', 'tasks',
    'customers', 'facebook-chat', 'line-connect',
    'facebook-ads', 'campaign-tracking', 'analytics', 'notification-rules',
    'courses', 'schedules', 'packages', 'attendance-scanner',
    'pos-system',
  ],

  // ── R4: Human Resource — employee management ────────────────────────────
  HR: [
    'executive-analytics',
    'employees', 'team-kpi', 'admin-performance', 'audit-trail',
    'tasks',
  ],

  // ── R5: Purchasing — PO + kitchen procurement ───────────────────────────
  PUR: [
    'executive-analytics', 'tasks',
    'kitchen-stock', 'inventory-control', 'procurement', 'assets',
    'inventory-manager',
  ],

  // ── R6: Warehouse / Production — kitchen + catalog + recipes ────────────
  PD: [
    'executive-analytics', 'tasks',
    'courses', 'schedules', 'recipes', 'packages', 'attendance-scanner',
    'kitchen-stock', 'inventory-control', 'procurement', 'assets',
    'inventory-manager',
  ],

  // ── R7: Admin / Doc — enrollment + documents ────────────────────────────
  ADM: [
    'executive-analytics',
    'pos-system',
    'customers', 'facebook-chat',
    'courses', 'schedules', 'packages', 'attendance-scanner',
    'tasks',
  ],

  // ── R8: Accounting — financial overview + reports (exec-level access) ───
  ACC: [
    'executive-analytics', 'tasks',
    'pos-system', 'inventory-manager',
    'customers',
    'facebook-ads', 'analytics',
    'audit-trail',
  ],

  // ── R9: Sales — POS + customers + inbox ─────────────────────────────────
  SLS: [
    'executive-analytics',
    'pos-system',
    'customers', 'facebook-chat', 'line-connect',
    'courses', 'schedules', 'packages', 'attendance-scanner',
    'tasks',
  ],

  // ── R10: Agent — inbox + own customers ──────────────────────────────────
  AGT: [
    'executive-analytics', 'tasks',
    'customers', 'facebook-chat', 'line-connect',
  ],

  // ── R11: Staff — POS + basic tasks ──────────────────────────────────────
  STF: [
    'executive-analytics',
    'pos-system',
    'tasks',
  ],
};

/**
 * canSeeItem(roleOrRoles, itemId) — called once per menu item at render time.
 *
 * Supports both single-role string (backward compat) and multi-role array.
 * Multi-role: returns true if ANY role in the array grants access (additive union).
 *
 * @param {string | string[]} roleOrRoles — from session.user.role or session.user.roles
 * @param {string}            itemId      — e.g. 'dashboard', 'facebook-ads'
 * @returns {boolean}
 */
export function canSeeItem(roleOrRoles, itemId) {
  // Normalise to array
  const roles = Array.isArray(roleOrRoles)
    ? roleOrRoles
    : [roleOrRoles];

  for (const r of roles) {
    const key = r?.toUpperCase?.() ?? r;
    const profile = SIDEBAR_PROFILES[key];
    if (profile === null || profile === undefined) return true; // null = full access
    if (profile.includes(itemId)) return true;
  }
  return false;
}

/**
 * getProfile(role) — returns the raw profile array (or null for full access).
 * For multi-role, use canSeeItem() instead.
 */
export function getProfile(role) {
  return SIDEBAR_PROFILES[role?.toUpperCase?.() ?? role] ?? null;
}

/**
 * getAllowedItems(roles[]) — returns union of all allowed item IDs across roles.
 * null in any role = full access (returns null to signal "show all").
 * @param {string[]} roles
 * @returns {string[] | null}
 */
export function getAllowedItems(roles) {
  const arr = Array.isArray(roles) ? roles : [roles];
  const union = new Set();
  for (const r of arr) {
    const profile = SIDEBAR_PROFILES[r?.toUpperCase?.() ?? r];
    if (profile === null || profile === undefined) return null; // full access
    profile.forEach(id => union.add(id));
  }
  return [...union];
}
