// ─── Generated by V School Menu Editor + Claude ──────────────────────────────
//
// USAGE IN Sidebar.js:
//   import { canSeeItem } from '@/lib/sidebarProfiles';
//
//   // Inside the render loop — checked once per item using session role:
//   if (!canSeeItem(userRole, item.id)) return null;
//
// RULE: items with active === false are always hidden (handled in Sidebar.js).
// RULE: null means "all items visible" for that role.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Role → allowed item IDs whitelist.
 * null  = all items visible (no filtering).
 * []    = no items visible.
 * [...]  = explicit whitelist of item IDs.
 */
export const SIDEBAR_PROFILES = {
  // ── Superusers — full access ────────────────────────────────────────────
  DEVELOPER: null,
  ADMIN:     null,

  // ── Owner — executive read-only: dashboard + analytics + finance ────────
  OWNER: [
    'dashboard', 'executive-analytics',
    'customers',
    'facebook-ads', 'campaign-tracking', 'analytics',
    'courses', 'schedules', 'packages',
    'inventory-control', 'procurement', 'assets',
    'employees', 'team-kpi', 'admin-performance', 'audit-trail',
  ],

  // ── Manager — all operational views, no system configuration ───────────
  MANAGER: [
    'dashboard', 'executive-analytics',
    'pos-system', 'inventory-manager', 'audit-trail',
    'customers', 'facebook-chat', 'line-connect',
    'facebook-ads', 'campaign-tracking', 'analytics', 'notification-rules',
    'courses', 'schedules', 'recipes', 'packages',
    'kitchen-stock', 'inventory-control', 'procurement', 'assets',
    'employees', 'tasks', 'team-kpi', 'admin-performance',
  ],

  // ── Marketing specialist — chat + ads + analytics ──────────────────────
  MARKETING: [
    'dashboard',
    'customers', 'facebook-chat', 'line-connect',
    'facebook-ads', 'campaign-tracking', 'analytics', 'notification-rules',
  ],

  // ── Head chef — kitchen + courses only ─────────────────────────────────
  HEAD_CHEF: [
    'dashboard',
    'courses', 'schedules', 'recipes', 'packages',
    'kitchen-stock', 'inventory-control', 'procurement', 'assets',
  ],

  // ── Employee — front-of-house operations ───────────────────────────────
  EMPLOYEE: [
    'dashboard',
    'pos-system',
    'customers', 'facebook-chat', 'line-connect',
    'courses', 'schedules',
    'tasks',
  ],

  // ── Agent — inbox only ─────────────────────────────────────────────────
  AGENT: [
    'dashboard',
    'customers', 'facebook-chat', 'line-connect',
  ],

  // ── Guest — dashboard only ─────────────────────────────────────────────
  GUEST: [
    'dashboard',
  ],
};

/**
 * canSeeItem(roleOrRoles, itemId) — called once per menu item at render time.
 *
 * Supports both single-role string (backward compat) and multi-role array.
 * Multi-role: returns true if ANY role in the array grants access (additive union).
 *
 * @param {string | string[]} roleOrRoles — from session.user.role or session.user.roles
 * @param {string}            itemId      — e.g. 'dashboard', 'facebook-ads'
 * @returns {boolean}
 */
export function canSeeItem(roleOrRoles, itemId) {
  // Normalise to array
  const roles = Array.isArray(roleOrRoles)
    ? roleOrRoles
    : [roleOrRoles];

  for (const r of roles) {
    const key = r?.toUpperCase?.() ?? r;
    const profile = SIDEBAR_PROFILES[key];
    if (profile === null || profile === undefined) return true; // null = full access
    if (profile.includes(itemId)) return true;
  }
  return false;
}

/**
 * getProfile(role) — returns the raw profile array (or null for full access).
 * For multi-role, use canSeeItem() instead.
 */
export function getProfile(role) {
  return SIDEBAR_PROFILES[role?.toUpperCase?.() ?? role] ?? null;
}

/**
 * getAllowedItems(roles[]) — returns union of all allowed item IDs across roles.
 * null in any role = full access (returns null to signal "show all").
 * @param {string[]} roles
 * @returns {string[] | null}
 */
export function getAllowedItems(roles) {
  const arr = Array.isArray(roles) ? roles : [roles];
  const union = new Set();
  for (const r of arr) {
    const profile = SIDEBAR_PROFILES[r?.toUpperCase?.() ?? r];
    if (profile === null || profile === undefined) return null; // full access
    profile.forEach(id => union.add(id));
  }
  return [...union];
}
